### ISSUE TITLE
FDM not working on Windows

### ISSUE THREAD

**Issue by mllightitup** [julianneswinoga/flightgear-python#4] opened 2023-03-11 03:43 UTC
I try to run a basic FDM example, but I get an error:

```
Traceback (most recent call last):
  File "C:\Users\Grishin\PycharmProjects\pythonProject1\FDM_TEST.py", line 25, in <module>
    fdm_conn.start()  # Start the FDM RX/TX loop
  File "C:\Users\Grishin\PycharmProjects\pythonProject1\venv\lib\site-packages\flightgear_python\fg_if.py", line 118, in start
    self.rx_proc.start()
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'construct.core.Pass'>: it's not the same object as construct.core.Pass

Process finished with exit code 1
```

What can I do to fix it?

python version: 3.8 (I also tested on 3.11.2 but nothing changed)
my start options: --fdm=null --max-fps=30 --native-fdm=socket,out,30,,5501,udp --native-fdm=socket,in,30,,5502,udp
When I work via telnet everything is fine

**Comment by julianneswinoga** [comment] 2023-03-11 16:15
Thanks for the bug report, I appreciate it! :smile: 

Ok, so I'm able to reproduce this and it seems that it's only a problem on Windows for some reason. Did you also get this error when running it?
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\...\lib\multiprocessing\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect
```

**Comment by mllightitup** [comment] 2023-03-11 18:23
I don't think so. This is all the error log I have.
I also realised that the error is the same whether the flight gear is running or not.

My friend has a different error, but from what I understand it is a normal error when the flight gear is off:
```
Traceback (most recent call last):
  File "C:\PYTHON\lib\site-packages\flightgear_python\fg_if.py", line 61, in connect_rx
    self.fg_rx_sock.bind(fg_rx_addr)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\PYTHON\lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-87ad27a78f0e>", line 1, in <module>
    runfile('C:/Users/BRINE/AppData/Roaming/JetBrains/PyCharm2022.2/scratches/scratch_4.py', wdir='C:/Users/BRINE/AppData/Roaming/JetBrains/PyCharm2022.2/scratches')
  File "C:\Program Files\JetBrains\PyCharm 2022.2\plugins\python\helpers\pydev_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2022.2\plugins\python\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/BRINE/AppData/Roaming/JetBrains/PyCharm2022.2/scratches/scratch_4.py", line 21, in <module>
    fdm_event_pipe = fdm_conn.connect_rx('localhost', 5501, fdm_callback)
  File "C:\PYTHON\lib\site-packages\flightgear_python\fg_if.py", line 63, in connect_rx
    raise FGConnectionError(f'Could not bind to {fg_rx_addr}: {e}')
flightgear_python.fg_util.FGConnectionError: Could not bind to ('localhost', 5501): [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

My full error log:
![image](https://user-images.githubusercontent.com/43480503/224504797-361f2158-2939-4b4c-b623-5b4f8819a7dc.png)

**Comment by julianneswinoga** [comment] 2023-03-12 15:09
Thanks for the info! I've released a new version (1.2.1) that I'm pretty sure will fix both of your issues (`Can't pickle...` and `Could not bind to`). Could you please update to that version and let me know if it's still crashing?

**Comment by mllightitup** [comment] 2023-03-13 03:48
I upgraded to the new version and used the code from the example simple_fdm.py and got this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Grishin\PycharmProjects\pythonProject1\FDM_TEST.py", line 24, in <module>
    fdm_conn.start()  # Start the FDM RX/TX loop
  File "C:\Users\Grishin\PycharmProjects\pythonProject1\venv\lib\site-packages\flightgear_python\fg_if.py", line 119, in start
    self.rx_proc.start()
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
Then I put all the code except the function under if __name__ == '__main__' and got this error:
```
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Grishin\PycharmProjects\pythonProject1\venv\lib\site-packages\flightgear_python\fg_if.py", line 84, in _fg_packet_roundtrip
    rx_msg, _ = self.fg_rx_sock.recvfrom(1024)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Grishin\PycharmProjects\pythonProject1\venv\lib\site-packages\flightgear_python\fg_if.py", line 112, in _rx_process
    self._fg_packet_roundtrip()
  File "C:\Users\Grishin\PycharmProjects\pythonProject1\venv\lib\site-packages\flightgear_python\fg_if.py", line 86, in _fg_packet_roundtrip
    raise FGConnectionError(f'Timeout waiting for data, waited {self.rx_timeout_s} seconds') from e
flightgear_python.fg_util.FGConnectionError: Timeout waiting for data, waited 2.0 seconds
```
Nothing is happening in flightgear at this point. And after I manually switched off the program, the error is complete with this:
```
Traceback (most recent call last):
  File "C:\Users\Grishin\PycharmProjects\pythonProject1\FDM_TEST.py", line 31, in <module>
    time.sleep(0.5)
KeyboardInterrupt
```
It all seems very strange. Could be a problem with some libraries or with pycharm itself.
Maybe something is corrupted or a problem with my system?
The errors in all cases also do not change depending on whether flight gear is on or off.

In addition I tried to run the simple_ctrls.py example and got an error like the first time:
```
Traceback (most recent call last):
  File "C:\Users\Grishin\PycharmProjects\pythonProject1\FDM_TEST.py", line 35, in <module>
    ctrls_conn.start()  # Start the Ctrls RX/TX loop
  File "C:\Users\Grishin\PycharmProjects\pythonProject1\venv\lib\site-packages\flightgear_python\fg_if.py", line 119, in start
    self.rx_proc.start()
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Grishin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'construct.core.Flag'>: it's not the same object as construct.core.Flag
```

**Comment by mllightitup** [comment] 2023-03-13 03:54
I just have a feeling that it's my system that's the problem or something, and I'm making you look for bugs in the code that might not be there. I will ask a friend to check on his system later today.

**Comment by julianneswinoga** [comment] 2023-03-13 18:15
Thanks again for the logs :smile:
No this is definitely a bug in `flightgear-python` (also a bug in `construct`: construct/construct#1018, but I'll fix that at a later time haha)
I've gone through and fully tested both the FDM and Ctrls interface on Windows and released a new version (`1.2.2`) that should work.

:warning: **Note that you need to change your user code!** :warning:
- You need to add `if __name__ == '__main__':` into your code, before you start executing stuff. This is due to how processes are created on Windows. (your code is actually `import`ed by the child process)
  - I've updated the examples to reflect this
- You need to explicitly specify `localhost` in your FlightGear socket options
  - I've also updated the docs for this

Let me know how it goes!

**Comment by mllightitup** [comment] 2023-03-13 22:12
Thank you very much, now everything works. But now I have a question. When I use code like this where essentially nothing happens over time or sometimes the plane starts jerking right away. Visually it looks like stutters but actually FlightGear itself works fine. It feels like the fdm_callback updates the entire model with a delay, and it becomes noticeable over time.

My code:
```
from flightgear_python.fg_if import FDMConnection


def fdm_callback(fdm_data, event_pipe):
    return fdm_data


if __name__ == '__main__':
    fdm_conn = FDMConnection(fdm_version=24)
    fdm_event_pipe = fdm_conn.connect_rx('localhost', 5501, fdm_callback)
    fdm_conn.connect_tx('localhost', 5502)
    fdm_conn.start()
```

Video:

https://user-images.githubusercontent.com/43480503/224843125-698d3528-9ca4-4c34-acc2-bc6fe7569bb6.mp4

**Comment by julianneswinoga** [comment] 2023-03-14 13:24
Fixed by #5 and #6

**Comment by julianneswinoga** [comment] 2023-03-14 13:24
Yeah that's expected when you didn't set `--fdm=null` in FG. The Flight Dynamics Model (FDM) interface is intended to **replace** the internal flight model. If you don't set `--fdm=null` you'll have *two* FDMs trying to set the aircraft state: the internal FDM and your custom Python FDM. More info here: https://wiki.flightgear.org/Flight_Dynamics_Model

Now even if you set `--fdm=null` there might still be some jerkyness in FG, I think this might be a bug in FG? I'm still investigating it and seeing if I can come up with a workaround on the Python end. It's got something to do with the order data is set and sent within FG.

**Closed by julianneswinoga** 2023-03-14 13:24 UTC
Labels: bug

**Comment by mllightitup** [comment] 2023-03-14 16:34
How is it possible to simply take data from FlighGear such as elevation, pitch, heading, roll, vertical speed? And use them in PID to get elevator signal without replacing the whole model. I want essentially the same behavior as with TELNET get_prop() and set_prop(), but only much faster to reduce "dt" in pid and response time.

**Comment by julianneswinoga** [comment] 2023-03-14 20:38
I've added an example: [simple_wing_level.py](/julianneswinoga/flightgear-python/blob/master/examples/simple_wing_level.py) that shows how that could work

**Comment by mllightitup** [comment] 2023-03-14 22:29
I thought about just not doing "return" in fdm_callback but didn't have time to check it. Thanks a lot for all this.
